name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['main']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Get tag version
      #   id: get_tag
      #   run: echo ::set-output name=PR_TAG_VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Get diff
        id: get_diff
        run: echo ::set-output name=PR_DIFF_TEXT::`git --no-pager log main..v0.0.0 --oneline`
      - name: Debug Envs
        run: echo ${{ steps.get_diff.outputs.DIFF_TEXT }}
        # env:
        #   BRANCH_NAME: ${{ steps.get_branch.outputs.PR_BRANCH_NAME }}
          # TAG_VERSION: ${{ steps.get_tag.outputs.PR_TAG_VERSION }}
          # DIFF_TEXT: ${{ steps.get_diff.outputs.PR_DIFF_TEXT }}
      # - name: Create a pull request
      #   uses: actions/github-script@v5
      #   env:
      #     BRANCH_NAME: ${{ steps.get_branch.outputs.PR_BRANCH_NAME }}
      #     TAG_VERSION: ${{ steps.get_tag.outputs.PR_TAG_VERSION }}
      #     DIFF_TEXT: ${{ steps.get_diff.outputs.PR_DIFF_TEXT }}
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       github.rest.pulls.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         title: `Pull request`,
      #         body: `Example body \n ${{process.env.DIFF_TEXT}} \n END`,
      #         head: 'kkkaoru:test-create-pr',
      #         base: 'main'
      #       })
