name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['main']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get branch name
        id: get_branch
        run: echo ::set-output name=PR_BRANCH_NAME::${GITHUB_HEAD_REF#refs/heads/}
      - name: Get tag version
        id: get_tag
        run: echo ::set-output name=PR_TAG_VERSION::${GITHUB_REF/refs\/tags\/v/}
      - name: Get diff
        id: get_diff
        run: echo ::set-output name=PR_DIFF_TEXT::`git --no-pager log ${BRANCH_NAME}..v${TAG_VERSION} --oneline`
        env:
          BRANCH_NAME: ${{ steps.get_branch.outputs.PR_BRANCH_NAME }}
          TAG_VERSION: ${{ steps.get_tag.outputs.PR_TAG_VERSION }}
      - name: Debug Envs
        run: echo ${BRANCH_NAME} && echo ${BRANCH_NAME} && echo ${DIFF_TEXT}
        env:
          BRANCH_NAME: ${{ steps.get_branch.outputs.PR_BRANCH_NAME }}
          TAG_VERSION: ${{ steps.get_tag.outputs.PR_TAG_VERSION }}
          DIFF_TEXT: ${{ steps.get_diff.outputs.PR_DIFF_TEXT }}
      - name: Create a pull request
        uses: actions/github-script@v5
        env:
          BRANCH_NAME: ${{ steps.get_branch.outputs.PR_BRANCH_NAME }}
          TAG_VERSION: ${{ steps.get_tag.outputs.PR_TAG_VERSION }}
          DIFF_TEXT: ${{ steps.get_diff.outputs.PR_DIFF_TEXT }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Pull request`,
              body: `Example body \n ${process.env.DIFF_TEXT}`,
              head: 'kkkaoru:test-create-pr',
              base: 'main'
            })
