name: Dump node version

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Dump node version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.18.4'
        run: node --version
