name: Dump ruby version

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Dump ruby version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Dump ruby version
        run: ruby --version
