name: HelloCI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Run Hello
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run hello
        run: ./hello.sh
